### ISSUE TITLE
Markdown images not rendered correctly in installation.md

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/tutorials#83]
The screenshot images for the bundle installation guide in [installation.md](https://github.com/napari/tutorials/blob/master/fundamentals/installation.md) are not rendering correctly.

We see this type of text, instead of the actual image:
```
An empty napari viewer should appear as follows

![image]({{ '/assets/tutorials/launch_cli_empty.png' | relative_url }})
```

**Comment by GenevieveBuckley** [comment]
Oh wait, images with the same markdown syntax are rendering on napari.org/tutorials

That's frustrating, if we can't render them properly in both places (but I see why napari.org is the first priority)

**Comment by jni** [comment]
Yeah, basically you need to install Jekyll locally to view things:

https://docs.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

My own earlier notes on this might also be useful, although many quirks have been fixed since I wrote it:

https://ilovesymposia.com/2015/01/04/some-things-i-learned-while-building-a-site-on-github-pages/

I guess this issue can be closed until we move to different infrastructure.
